# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbase.proto\x12\x04\x62\x61se\"\xb1\x02\n\x0fNetatmoMessages\x1a\x10\n\x0eNetatmoRequest\x1as\n\x0bNetatmoData\x12\x30\n\x06indoor\x18\x01 \x01(\x0b\x32 .base.NetatmoMessages.IndoorData\x12\x32\n\x07outdoor\x18\x02 \x01(\x0b\x32!.base.NetatmoMessages.OutdoorData\x1a\x61\n\nIndoorData\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x0b\n\x03\x43O2\x18\x02 \x01(\x02\x12\x10\n\x08humidity\x18\x03 \x01(\x02\x12\r\n\x05noise\x18\x04 \x01(\x02\x12\x10\n\x08pressure\x18\x05 \x01(\x02\x1a\x34\n\x0bOutdoorData\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08humidity\x18\x02 \x01(\x02\"\x9b\x01\n\rImageMessages\x1a@\n\x0cImageRequest\x12\x11\n\timageType\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x1aH\n\tImageData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x32_\n\x07Netatmo\x12T\n\x07GetData\x12$.base.NetatmoMessages.NetatmoRequest\x1a!.base.NetatmoMessages.NetatmoData\"\x00\x32V\n\x05Image\x12M\n\x08GetImage\x12 .base.ImageMessages.ImageRequest\x1a\x1d.base.ImageMessages.ImageData\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'base_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NETATMOMESSAGES._serialized_start=21
  _NETATMOMESSAGES._serialized_end=326
  _NETATMOMESSAGES_NETATMOREQUEST._serialized_start=40
  _NETATMOMESSAGES_NETATMOREQUEST._serialized_end=56
  _NETATMOMESSAGES_NETATMODATA._serialized_start=58
  _NETATMOMESSAGES_NETATMODATA._serialized_end=173
  _NETATMOMESSAGES_INDOORDATA._serialized_start=175
  _NETATMOMESSAGES_INDOORDATA._serialized_end=272
  _NETATMOMESSAGES_OUTDOORDATA._serialized_start=274
  _NETATMOMESSAGES_OUTDOORDATA._serialized_end=326
  _IMAGEMESSAGES._serialized_start=329
  _IMAGEMESSAGES._serialized_end=484
  _IMAGEMESSAGES_IMAGEREQUEST._serialized_start=346
  _IMAGEMESSAGES_IMAGEREQUEST._serialized_end=410
  _IMAGEMESSAGES_IMAGEDATA._serialized_start=412
  _IMAGEMESSAGES_IMAGEDATA._serialized_end=484
  _NETATMO._serialized_start=486
  _NETATMO._serialized_end=581
  _IMAGE._serialized_start=583
  _IMAGE._serialized_end=669
# @@protoc_insertion_point(module_scope)
