# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: netatmo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnetatmo.proto\x12\x07netatmo\"\x10\n\x0eNetatmoRequest\"Y\n\x0bNetatmoData\x12#\n\x06indoor\x18\x01 \x01(\x0b\x32\x13.netatmo.IndoorData\x12%\n\x07outdoor\x18\x02 \x01(\x0b\x32\x14.netatmo.OutdoorData\"a\n\nIndoorData\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x0b\n\x03\x43O2\x18\x02 \x01(\x02\x12\x10\n\x08humidity\x18\x03 \x01(\x02\x12\r\n\x05noise\x18\x04 \x01(\x02\x12\x10\n\x08pressure\x18\x05 \x01(\x02\"4\n\x0bOutdoorData\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08humidity\x18\x02 \x01(\x02\x32\x45\n\x07Netatmo\x12:\n\x07GetData\x12\x17.netatmo.NetatmoRequest\x1a\x14.netatmo.NetatmoData\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'netatmo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NETATMOREQUEST._serialized_start=26
  _NETATMOREQUEST._serialized_end=42
  _NETATMODATA._serialized_start=44
  _NETATMODATA._serialized_end=133
  _INDOORDATA._serialized_start=135
  _INDOORDATA._serialized_end=232
  _OUTDOORDATA._serialized_start=234
  _OUTDOORDATA._serialized_end=286
  _NETATMO._serialized_start=288
  _NETATMO._serialized_end=357
# @@protoc_insertion_point(module_scope)
